apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
spec:
  name: {{ include "rosa-aws-prometheus.fullname" . }}.yaml
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      sigV4Auth: true
      sigV4Region: {{ .Values.aws.region }}
    name: prometheus
    type: prometheus
    url: 'https://aps-workspaces.{{ .Values.aws.region }}.amazonaws.com/workspaces/{{ .Values.aws.workspaceId }}'
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "rosa-aws-prometheus.fullname" . }}-cloudwatch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosa-aws-prometheus.labels" . | nindent 4 }}
spec:
  datasource:
    access: proxy
    editable: false
    isDefault: false
    name: cloudwatch
    type: cloudwatch
    jsonData:
      defaultRegion: us-east-2
      authType: default
  name: cloudwatch.yaml
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
